// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"time"
)

type BotVisit struct {
	ID        int64
	BotName   string
	IpHash    string
	UserAgent string
	Path      string
	Timestamp time.Time
}

type Setting struct {
	Key   string
	Value string
}

type Visit struct {
	ID          int64
	VisitorID   string
	SessionID   string
	IpHash      string
	Browser     string
	Os          string
	Device      string
	Path        string
	Referrer    sql.NullString
	ScreenSize  sql.NullString
	Timestamp   time.Time
	DurationSec sql.NullInt64
}
