// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const avgDuration = `-- name: AvgDuration :one
SELECT AVG(duration_sec) FROM visits WHERE timestamp >= ? AND timestamp < ? AND duration_sec > 0
`

func (q *Queries) AvgDuration(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) (sql.NullFloat64, error) {
	row := q.db.QueryRowContext(ctx, avgDuration, timestamp, timestamp_2)
	var avg sql.NullFloat64
	err := row.Scan(&avg)
	return avg, err
}

const browserStats = `-- name: BrowserStats :many
SELECT browser AS name, COUNT(*) AS count
FROM visits
WHERE timestamp >= ? AND timestamp < ?
GROUP BY browser
ORDER BY count DESC
`

type BrowserStatsRow struct {
	Name  string
	Count int64
}

func (q *Queries) BrowserStats(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]BrowserStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, browserStats, timestamp, timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BrowserStatsRow
	for rows.Next() {
		var i BrowserStatsRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBotVisits = `-- name: CountBotVisits :one

SELECT COUNT(*) FROM bot_visits WHERE timestamp >= ? AND timestamp < ?
`

// Bot aggregations
func (q *Queries) CountBotVisits(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBotVisits, timestamp, timestamp_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRealtimeVisitors = `-- name: CountRealtimeVisitors :one

SELECT COUNT(DISTINCT visitor_id) FROM visits WHERE timestamp >= ?
`

// Realtime
func (q *Queries) CountRealtimeVisitors(ctx context.Context, timestamp time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRealtimeVisitors, timestamp)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUniqueVisitors = `-- name: CountUniqueVisitors :one
SELECT COUNT(DISTINCT visitor_id) FROM visits WHERE timestamp >= ? AND timestamp < ?
`

func (q *Queries) CountUniqueVisitors(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUniqueVisitors, timestamp, timestamp_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVisits = `-- name: CountVisits :one

SELECT COUNT(*) FROM visits WHERE timestamp >= ? AND timestamp < ?
`

// Visitor aggregations
func (q *Queries) CountVisits(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVisits, timestamp, timestamp_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dailyBotVisits = `-- name: DailyBotVisits :many
SELECT CAST(substr(timestamp, 1, 10) AS TEXT) AS date, COUNT(*) AS views
FROM bot_visits
WHERE timestamp >= ? AND timestamp < ?
GROUP BY 1
ORDER BY date
`

type DailyBotVisitsRow struct {
	Date  string
	Views int64
}

func (q *Queries) DailyBotVisits(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]DailyBotVisitsRow, error) {
	rows, err := q.db.QueryContext(ctx, dailyBotVisits, timestamp, timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyBotVisitsRow
	for rows.Next() {
		var i DailyBotVisitsRow
		if err := rows.Scan(&i.Date, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dailyViews = `-- name: DailyViews :many
SELECT CAST(substr(timestamp, 1, 10) AS TEXT) AS date, COUNT(*) AS views
FROM visits
WHERE timestamp >= ? AND timestamp < ?
GROUP BY 1
ORDER BY date
`

type DailyViewsRow struct {
	Date  string
	Views int64
}

func (q *Queries) DailyViews(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]DailyViewsRow, error) {
	rows, err := q.db.QueryContext(ctx, dailyViews, timestamp, timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyViewsRow
	for rows.Next() {
		var i DailyViewsRow
		if err := rows.Scan(&i.Date, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteOldBotVisits = `-- name: DeleteOldBotVisits :exec
DELETE FROM bot_visits WHERE timestamp < ?
`

func (q *Queries) DeleteOldBotVisits(ctx context.Context, timestamp time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteOldBotVisits, timestamp)
	return err
}

const deleteOldVisits = `-- name: DeleteOldVisits :exec

DELETE FROM visits WHERE timestamp < ?
`

// Cleanup
func (q *Queries) DeleteOldVisits(ctx context.Context, timestamp time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteOldVisits, timestamp)
	return err
}

const deviceStats = `-- name: DeviceStats :many
SELECT device AS name, COUNT(*) AS count
FROM visits
WHERE timestamp >= ? AND timestamp < ?
GROUP BY device
ORDER BY count DESC
`

type DeviceStatsRow struct {
	Name  string
	Count int64
}

func (q *Queries) DeviceStats(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]DeviceStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, deviceStats, timestamp, timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceStatsRow
	for rows.Next() {
		var i DeviceStatsRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSetting = `-- name: GetSetting :one

SELECT value FROM settings WHERE key = ?
`

// Settings
func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const hourlyBotVisits = `-- name: HourlyBotVisits :many
SELECT CAST(substr(timestamp, 12, 2) || ':00' AS TEXT) AS date, COUNT(*) AS views
FROM bot_visits
WHERE timestamp >= ? AND timestamp < ?
GROUP BY 1
ORDER BY date
`

type HourlyBotVisitsRow struct {
	Date  string
	Views int64
}

func (q *Queries) HourlyBotVisits(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]HourlyBotVisitsRow, error) {
	rows, err := q.db.QueryContext(ctx, hourlyBotVisits, timestamp, timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HourlyBotVisitsRow
	for rows.Next() {
		var i HourlyBotVisitsRow
		if err := rows.Scan(&i.Date, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hourlyViews = `-- name: HourlyViews :many
SELECT CAST(substr(timestamp, 12, 2) || ':00' AS TEXT) AS date, COUNT(*) AS views
FROM visits
WHERE timestamp >= ? AND timestamp < ?
GROUP BY 1
ORDER BY date
`

type HourlyViewsRow struct {
	Date  string
	Views int64
}

func (q *Queries) HourlyViews(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]HourlyViewsRow, error) {
	rows, err := q.db.QueryContext(ctx, hourlyViews, timestamp, timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HourlyViewsRow
	for rows.Next() {
		var i HourlyViewsRow
		if err := rows.Scan(&i.Date, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBotVisit = `-- name: InsertBotVisit :exec
INSERT INTO bot_visits (bot_name, ip_hash, user_agent, path, timestamp)
VALUES (?, ?, ?, ?, ?)
`

type InsertBotVisitParams struct {
	BotName   string
	IpHash    string
	UserAgent string
	Path      string
	Timestamp time.Time
}

func (q *Queries) InsertBotVisit(ctx context.Context, arg InsertBotVisitParams) error {
	_, err := q.db.ExecContext(ctx, insertBotVisit,
		arg.BotName,
		arg.IpHash,
		arg.UserAgent,
		arg.Path,
		arg.Timestamp,
	)
	return err
}

const insertVisit = `-- name: InsertVisit :exec

INSERT INTO visits (visitor_id, session_id, ip_hash, browser, os, device, path, referrer, screen_size, timestamp, duration_sec)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertVisitParams struct {
	VisitorID   string
	SessionID   string
	IpHash      string
	Browser     string
	Os          string
	Device      string
	Path        string
	Referrer    sql.NullString
	ScreenSize  sql.NullString
	Timestamp   time.Time
	DurationSec sql.NullInt64
}

// Inserts
func (q *Queries) InsertVisit(ctx context.Context, arg InsertVisitParams) error {
	_, err := q.db.ExecContext(ctx, insertVisit,
		arg.VisitorID,
		arg.SessionID,
		arg.IpHash,
		arg.Browser,
		arg.Os,
		arg.Device,
		arg.Path,
		arg.Referrer,
		arg.ScreenSize,
		arg.Timestamp,
		arg.DurationSec,
	)
	return err
}

const latestPages = `-- name: LatestPages :many
SELECT path, timestamp, browser
FROM visits
WHERE timestamp >= ? AND timestamp < ?
ORDER BY timestamp DESC
LIMIT 5
`

type LatestPagesRow struct {
	Path      string
	Timestamp time.Time
	Browser   string
}

func (q *Queries) LatestPages(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]LatestPagesRow, error) {
	rows, err := q.db.QueryContext(ctx, latestPages, timestamp, timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestPagesRow
	for rows.Next() {
		var i LatestPagesRow
		if err := rows.Scan(&i.Path, &i.Timestamp, &i.Browser); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlyBotVisits = `-- name: MonthlyBotVisits :many
SELECT CAST(substr(timestamp, 1, 7) AS TEXT) AS date, COUNT(*) AS views
FROM bot_visits
WHERE timestamp >= ? AND timestamp < ?
GROUP BY 1
ORDER BY date
`

type MonthlyBotVisitsRow struct {
	Date  string
	Views int64
}

func (q *Queries) MonthlyBotVisits(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]MonthlyBotVisitsRow, error) {
	rows, err := q.db.QueryContext(ctx, monthlyBotVisits, timestamp, timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyBotVisitsRow
	for rows.Next() {
		var i MonthlyBotVisitsRow
		if err := rows.Scan(&i.Date, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlyViews = `-- name: MonthlyViews :many
SELECT CAST(substr(timestamp, 1, 7) AS TEXT) AS date, COUNT(*) AS views
FROM visits
WHERE timestamp >= ? AND timestamp < ?
GROUP BY 1
ORDER BY date
`

type MonthlyViewsRow struct {
	Date  string
	Views int64
}

func (q *Queries) MonthlyViews(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]MonthlyViewsRow, error) {
	rows, err := q.db.QueryContext(ctx, monthlyViews, timestamp, timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyViewsRow
	for rows.Next() {
		var i MonthlyViewsRow
		if err := rows.Scan(&i.Date, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oSStats = `-- name: OSStats :many
SELECT os AS name, COUNT(*) AS count
FROM visits
WHERE timestamp >= ? AND timestamp < ?
GROUP BY os
ORDER BY count DESC
`

type OSStatsRow struct {
	Name  string
	Count int64
}

func (q *Queries) OSStats(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]OSStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, oSStats, timestamp, timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OSStatsRow
	for rows.Next() {
		var i OSStatsRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const referrerStats = `-- name: ReferrerStats :many
SELECT
    CASE
        WHEN referrer = '' OR referrer IS NULL THEN 'Direct'
        WHEN referrer LIKE '%google.%' THEN 'Google'
        WHEN referrer LIKE '%bing.%' THEN 'Bing'
        WHEN referrer LIKE '%duckduckgo.%' THEN 'DuckDuckGo'
        WHEN referrer LIKE '%yahoo.%' THEN 'Yahoo'
        WHEN referrer LIKE '%github.%' THEN 'GitHub'
        ELSE 'Other'
    END AS name,
    COUNT(*) AS count
FROM visits
WHERE timestamp >= ? AND timestamp < ?
GROUP BY 1
ORDER BY count DESC
`

type ReferrerStatsRow struct {
	Name  string
	Count int64
}

func (q *Queries) ReferrerStats(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]ReferrerStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, referrerStats, timestamp, timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReferrerStatsRow
	for rows.Next() {
		var i ReferrerStatsRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topBotPages = `-- name: TopBotPages :many
SELECT path, COUNT(*) AS views
FROM bot_visits
WHERE timestamp >= ? AND timestamp < ?
GROUP BY path
ORDER BY views DESC
LIMIT 10
`

type TopBotPagesRow struct {
	Path  string
	Views int64
}

func (q *Queries) TopBotPages(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]TopBotPagesRow, error) {
	rows, err := q.db.QueryContext(ctx, topBotPages, timestamp, timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopBotPagesRow
	for rows.Next() {
		var i TopBotPagesRow
		if err := rows.Scan(&i.Path, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topBots = `-- name: TopBots :many
SELECT bot_name AS name, COUNT(*) AS count
FROM bot_visits
WHERE timestamp >= ? AND timestamp < ?
GROUP BY bot_name
ORDER BY count DESC
LIMIT 10
`

type TopBotsRow struct {
	Name  string
	Count int64
}

func (q *Queries) TopBots(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]TopBotsRow, error) {
	rows, err := q.db.QueryContext(ctx, topBots, timestamp, timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopBotsRow
	for rows.Next() {
		var i TopBotsRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topPages = `-- name: TopPages :many
SELECT path, COUNT(*) AS views
FROM visits
WHERE timestamp >= ? AND timestamp < ?
GROUP BY path
ORDER BY views DESC
LIMIT 10
`

type TopPagesRow struct {
	Path  string
	Views int64
}

func (q *Queries) TopPages(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]TopPagesRow, error) {
	rows, err := q.db.QueryContext(ctx, topPages, timestamp, timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopPagesRow
	for rows.Next() {
		var i TopPagesRow
		if err := rows.Scan(&i.Path, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVisitDuration = `-- name: UpdateVisitDuration :exec

UPDATE visits SET duration_sec = ?
WHERE id = (
  SELECT v.id FROM visits v
  WHERE v.visitor_id = ? AND v.path = ?
  ORDER BY v.timestamp DESC
  LIMIT 1
)
`

type UpdateVisitDurationParams struct {
	DurationSec sql.NullInt64
	VisitorID   string
	Path        string
}

// Duration update
func (q *Queries) UpdateVisitDuration(ctx context.Context, arg UpdateVisitDurationParams) error {
	_, err := q.db.ExecContext(ctx, updateVisitDuration, arg.DurationSec, arg.VisitorID, arg.Path)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

func (q *Queries) UpsertSetting(ctx context.Context, key string, value string) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, key, value)
	return err
}
