// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AvgDuration(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) (sql.NullFloat64, error)
	BrowserStats(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]BrowserStatsRow, error)
	// Bot aggregations
	CountBotVisits(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) (int64, error)
	// Realtime
	CountRealtimeVisitors(ctx context.Context, timestamp time.Time) (int64, error)
	CountUniqueVisitors(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) (int64, error)
	// Visitor aggregations
	CountVisits(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) (int64, error)
	DailyBotVisits(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]DailyBotVisitsRow, error)
	DailyViews(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]DailyViewsRow, error)
	DeleteOldBotVisits(ctx context.Context, timestamp time.Time) error
	// Cleanup
	DeleteOldVisits(ctx context.Context, timestamp time.Time) error
	DeviceStats(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]DeviceStatsRow, error)
	// Settings
	GetSetting(ctx context.Context, key string) (string, error)
	HourlyBotVisits(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]HourlyBotVisitsRow, error)
	HourlyViews(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]HourlyViewsRow, error)
	InsertBotVisit(ctx context.Context, arg InsertBotVisitParams) error
	// Inserts
	InsertVisit(ctx context.Context, arg InsertVisitParams) error
	LatestPages(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]LatestPagesRow, error)
	MonthlyBotVisits(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]MonthlyBotVisitsRow, error)
	MonthlyViews(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]MonthlyViewsRow, error)
	OSStats(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]OSStatsRow, error)
	ReferrerStats(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]ReferrerStatsRow, error)
	TopBotPages(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]TopBotPagesRow, error)
	TopBots(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]TopBotsRow, error)
	TopPages(ctx context.Context, timestamp time.Time, timestamp_2 time.Time) ([]TopPagesRow, error)
	// Duration update
	UpdateVisitDuration(ctx context.Context, arg UpdateVisitDurationParams) error
	UpsertSetting(ctx context.Context, key string, value string) error
}

var _ Querier = (*Queries)(nil)
