# Load .env if it exists (copy .env.example to .env to get started).
-include .env
export

TAILWINDCSS := node_modules/.bin/tailwindcss
ESBUILD := node_modules/.bin/esbuild
TAILWIND_INPUT := assets/tailwind.css
TAILWIND_OUTPUT := public/tailwind.css
JS_INPUT := src/app.js
JS_OUTPUT := public/app.min.js
TEMPL := $(shell go env GOPATH)/bin/templ

.PHONY: css css-prod js templ run prod test build-linux

css: $(TAILWIND_OUTPUT)

$(TAILWIND_OUTPUT): $(TAILWIND_INPUT) tailwind.config.js package-lock.json | $(TAILWINDCSS)
	$(TAILWINDCSS) -i $(TAILWIND_INPUT) -o $(TAILWIND_OUTPUT) --minify

css-prod: $(TAILWIND_INPUT) tailwind.config.js package-lock.json | $(TAILWINDCSS)
	NODE_ENV=production $(TAILWINDCSS) -i $(TAILWIND_INPUT) -o $(TAILWIND_OUTPUT) --minify

js: $(JS_OUTPUT)

$(JS_OUTPUT): $(JS_INPUT) | $(ESBUILD)
	$(ESBUILD) $(JS_INPUT) --bundle --minify --outfile=$(JS_OUTPUT)

$(TAILWINDCSS) $(ESBUILD):
	npm install

templ:
	$(TEMPL) generate
	go mod tidy

run: templ css js
	go run .

prod: templ css-prod js
	go run .

test:
	go test ./...

build-linux: templ css-prod js
	GOOS=linux GOARCH=amd64 go build -o {{.ProjectName}} .
